# Generated by Django 4.2.4 on 2023-08-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(upload_to='img', verbose_name='Photo'),
        ),
    ]
